# This is the file of expected results for nisttest.py
test01 verified
test02 signature_error
test03 signature_error
test04 verified
test05 cert_not_yet_valid
test06 cert_not_yet_valid
test07 verified
test08 cert_not_yet_valid
test09 cert_has_expired
test10 cert_has_expired
test11 cert_has_expired
test12 verified
test13 cert_issuer_not_found
test14 cert_issuer_not_found
test15 verified
test16 verified
test17 verified
test18 verified
# changed; should be no_revocation_data_available, but I don't want to
# force people to use CRLs
test19 verified
test20 cert_is_revoked
test21 cert_is_revoked
test22 ca_cert_not_for_cert_issuer
test23 ca_cert_not_for_cert_issuer
test24 verified
test25 ca_cert_not_for_cert_issuer
test26 verified
test27 verified
test28 ca_cert_not_for_cert_issuer
test29 ca_cert_not_for_cert_issuer
test30 verified
test31 ca_cert_not_for_crl_issuer
test32 ca_cert_not_for_crl_issuer
test33 verified
test54 cert_chain_too_long
test55 cert_chain_too_long
test56 verified
test57 verified
test58 cert_chain_too_long
test59 cert_chain_too_long
test60 cert_chain_too_long
test61 cert_chain_too_long
test62 verified
test63 verified
test64 signature_error
# changed; I have no idea why this test is supposed to fail
test65 verified
test66 crl_issuer_not_found
# changed; one of the CRLs has an unknown creator, so we fail
# prior to getting to the end-entity check
test67 crl_issuer_not_found
test68 cert_is_revoked
test69 cert_is_revoked
test70 cert_is_revoked
test71 cert_is_revoked
test72 crl_has_expired
test73 crl_has_expired
test74 verified
